Repository ginabeki/Catalog-App, pull requests merged in 2023-02, with the labels that each got.

#23 Catalog App: Create entry point file
  app.rb
  main.rb
Labels: enhancement

#22 Catalog-App : Item Class
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .rubocop.yml
  Gemfile.lock
  MIT.md
  README.md
  app.rb
  classes/item.rb
  main.rb
  pull_request_template.md
Labels: enhancement

#27 Catalog App : Game Class
  classes/game.rb
Labels: enhancement

#28 Catalog App : Author Class
  classes/author.rb
  classes/item.rb
Labels: enhancement

#31 Catalog App : Unit test Game and Author
  classes/game.rb
  classes/item.rb
  spec/author_spec.rb
  spec/game_spec.rb
  spec/music_album_spec.rb
Labels: Test

#32 Preserve data for book and label class
  .rubocop.yml
  README.md
  app.rb
  classes/book.rb
  classes/book_label.rb
  classes/label.rb
  data/book.json
  data/label.json
Labels: enhancement

#33 Catalog App : Add options for Game and Author
  app.rb
  utilities/author_utility.rb
  utilities/game_utility.rb
Labels: enhancement

#34 Catalog App: Persist data for Games and Authors
  app.rb
  json_data/authors.json
  json_data/games.json
  utilities/author_utility.rb
  utilities/game_utility.rb
Labels: enhancement

#37 Catalog App: Persist data in Book and Label class
  json_data/book.json
  json_data/label.json
  utilities/book_label.rb
Labels: enhancement

#40 Catalog App: Add Schema for Game and Author
  schema.sql
Labels: database

#42 Catalog App V0.1
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  LICENCE
  MIT.md
  README.md
  app.rb
  app_screenshot.png
  classes/author.rb
  classes/book.rb
  classes/game.rb
  classes/genre.rb
  classes/item.rb
  classes/label.rb
  classes/music_album.rb
  json_data/album.json
  json_data/authors.json
  json_data/book.json
  json_data/games.json
  json_data/genre.json
  json_data/label.json
  main.rb
  murple_logo.png
  pull_request_template.md
  schema.sql
  spec/author_spec.rb
  spec/book_spec.rb
  spec/game_spec.rb
  spec/genre_spec.rb
  spec/label_spec.rb
  spec/music_album_spec.rb
  spec/spec_helper.rb
  utilities/author_utility.rb
  utilities/book_label.rb
  utilities/game_utility.rb
  utilities/handle_musicalbum.rb
Labels: Release
